default:
    image: haskell-ib015:v1.2
    before_script:
            - apt-get update
            - apt-get install -y libllvm7

.template:
    except:
        variables:
            - $CI_COMMIT_MESSAGE =~ /\bno[-_]?ci\b/
    tags:
        - shared-fi

build:
    extends: .template
    stage: build
    script:
        - apt-get install -y clang clang-tools flex bison libfl-dev
        - make seagolc
    when: always
    artifacts:
        name: "binary"
        paths:
            - seagolc
        expire_in: 20 minutes

test:
    extends: .template
    stage: test
    script:
        - make test

linkage:
    extends: .template
    stage: test
    script:
        - apt-get install -y clang
        - make demos
        - demo/sorts
